/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE   (*(volatile unsigned int*)0x40021000)
#define RCC_APB2ENR   (*(volatile unsigned int*)0x40021018)
#define GPIOC_CRH     (*(volatile unsigned int*)0x40011004)
#define GPIOC_ODR     (*(volatile unsigned int*)0x4001100C)
#define LED_PIN       13         // PC13

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay(volatile unsigned int t) {
    while(t--);
}


int main(void)
{
	RCC_APB2ENR |= (1 << 4);
	GPIOC_CRH &= ~(0xF << 20); //xoá cấu hình gpio 13 bit20-23 0000
	GPIOC_CRH |= (0x1 << 20); //set mode13 = 01, cnf = 00 bit 20-23 0001
    /* Loop forever */
	for(;;){
		GPIOC_ODR &= ~(0x1 << 13); //TẮT LED
		delay(5000000);
		GPIOC_ODR |= (0x1 << 13); //Bật led
		delay(5000000);
	}
}
